# Config file for CelebA dataset (200k)

output_dir: 'I:/model_ckpts/styleGAN4naip/codes_copy/01'
structure: 'linear'
device_id: ('0')
dataset:
  img_dir: 'I:/data/NAIP4StyleGAN/naip_512'
  folder: False
  resolution: 128
sched:
  epochs: [2,4,4,4,4,8]
